from .views import (
    Business_Optimization_Consulting,
    Strategy_and_Consulting,
    Technology_Strategy,
    product_strategy,
    learning_and_development,
    advanced_technology,
    robotic_process_automation,
    internet_of_things,
    blockchain,
    ar_vr
)
from django.urls import path

urlpatterns = [
    path('strategy-and-consulting/',
           Strategy_and_Consulting,
           name='strategy_and_consulting'),
    path('strategy_&_consulting/business-optimization-consulting/',
            Business_Optimization_Consulting,
            name='business_optimization_consulting'),
    path('strategy_&_consulting/product-strategy/',
            product_strategy,
            name='product_strategy'),
    path('strategy_&_consulting/technology-strategy/',
            Technology_Strategy,
            name='technology_strategy'),
    path('strategy_&_consulting/learning-and-development/',
            learning_and_development,
            name='learning_and_development'),
    path('advanced-technology/',
            advanced_technology,
            name='advanced_technology'),
    path('advanced-technology/robotic-process-automation/',
            robotic_process_automation,
            name='robotic_process_automation'),
    path('advanced-technology/internet-of-things/',
            internet_of_things,
            name='internet_of_things'),
    path('advanced-technology/blockchain/',
            blockchain,
            name='blockchain'),
    path('advanced-technology/ar-vr/',
            ar_vr,
            name='ar_vr'),        
]