# Generated by Django 6.0.6 on 2026-07-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='team',
            name='display_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
